ML-PLIC-Local/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include
from django.views import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('plic/', include('cal_docking.urls')),
    path('plic/', include('cal_descriptors.urls')),
    path('plic/', include('cal_model.urls')),
    path('plic/', include('cal_screening.urls')),
    path('plic/', include('cal_pipline.urls')),
    path('plic/', include('cal_queue.urls')),
    # 通过URL获取分子图片等文件
    re_path(r'^plic/submitted_files/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    # 获取静态文件
    re_path(r'^plic/static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
]

cal_model/urls.py
#!usr/bin/env python
# -*- coding:utf-8 -*-
from django.urls import path
from . import views
app_name = 'cal_model'
urlpatterns = [
    path('modelling/', views.main, name='modelling')
]

cal_queue/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# author = zhang xujun
# time = 2020-07-18
from django.urls import path, re_path
from . import views
app_name = 'cal_queue'
urlpatterns = [
    path('queue', views.queue_page, name='queue'),  # 队列
    path('help', views.help, name='help'),  # 帮助
    path('paper', views.paper, name='paper'),  # 文章
    path('contact', views.contact, name='contact'),  # 联系
    path('viewed', views.viewed, name='viewed'),  # IP访问次数
    re_path(r'^results/(?P<job_id>job_[0-9]{8})', views.check_key, name='result'),  # 验证表单
    re_path(r'^results/(?P<job_id>b.*cadd$)', views.show_result, name='result_show'),  # 结果界面
    re_path(r'^results/(?P<job_id>b.*cadd)/download', views.download_result, name='download'),  # 结果界面下载结果文件
    re_path(r'^temp/job.*', views.temp, name='temp'),  # 各个任务完成后转跳的空白界面
    re_path(r'^temp/download/(?P<job_id>.*)', views.generate_key, name='generate_key'),  # 空白界面下载密钥
    re_path(r'^example/(?P<file_name>.*)', views.example_download, name='example_download'),  # 下载example 文件
]

cal_screening/urls.py
#!usr/bin/env python
# -*- coding:utf-8 -*-
# author = zhang xujun
# time = 2020-07-15

from django.urls import path
from . import views
app_name = 'cal_screening'
urlpatterns = [
    path('screening/', views.main, name='screening')
]

cal_screening/models.py
from django.db import models

# Create your models here.

cal_screening/views.py
from django.shortcuts import render

# Create your views here.
import os
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from base_scripts.base_class import global_base


def main(request):
    # 若提交表单，则进行计算
    if request.method == 'POST':
        # 生成任务id
        id_name = global_base.job_generation().get_id()
        # 实例化对象
        this_job = global_base.screening_control(id_name)
        # 创建任务路径
        path_job = this_job.path_job
        # 创建csv文件存放路径
        path_csvs = this_job.path_for_csv
        # 创建日志路径
        path_log = this_job.path_for_log
        # 创建配置文件路径
        path_config = this_job.path_for_config
        # 创建报告路径
        path_report = this_job.path_for_report
        # 创建文件夹
        for dir in [path_job, path_config, path_csvs, path_log, path_report]:
            os.mkdir(dir)
        # 循环上传csv小分子文件, 在前端要求上传文件, 'descriptor_file', 'test_descriptor_file''config_file' 必须上传
        for input_name in ['descriptor_file', 'test_descriptor_file', 'config_file']:
            this_job.handle_uploaded_file(request, input_name, path_csvs)
        # 把表单记录到文件中传递参数
        form_dic = request.POST.dict()  # POST转成字典
        del form_dic['csrfmiddlewaretoken']  # 删除csrf键
        con = '''{}\n{}\n'''.format(this_job.job_type, form_dic)  # 组装内容
        this_job.write_config(con)  # 写入文件
        # 提交任务
        this_job.submit_job(request, id_name, path_log)
        # 重定向获取密钥
        return HttpResponseRedirect('../temp/{}'.format(id_name))
    # 未提交表单，渲染正常页面
    else:
        # 获取访问量
        this_job = global_base.job_generation()
        total_viewed = this_job.get_total_viewed()
        context = {'total_viewed': total_viewed}
        return HttpResponse(render(request, 'screening/index.html', context))

cal_screening/templates/screening/index.html
<!--继承模板-->
{% extends 'descriptors/base.html' %}

<!--修改标题-->
{% block title %}
    <title>screening</title>
{% endblock %}
<!--修改内容-->
<!--巨幕-->
{% block jumbotron %}
    <h1 style="margin-top: 10px">Virtual Screening</h1>
    <p class="text-justify">
        In this module, the server provides a virtual screening service at high speed with the support of 28 CPU cores.
        <br><br>The config file is one of the result files of the <span class="text-primary">Modelling</span> module
        and contains the best model built by the modelling process. The training set descriptor file provides the names
        of ligands, descriptors characterizing protein-ligand interaction and the labels of each ligand while the test
        set provides the same information but no labels.
        <br><br>In a standard process of virtual screening using this server, the descriptors of the training set and
        test
        set should be generated in the <span class="text-primary">Descriptors</span> module and the config file should
        be generated in the <span class="text-primary">Modelling</span> module. Actually, as long as the data structure
        of data in the descriptor file is like</p>
    <pre>name, desctiptor_1, descriptor_2, ..., descriptor_n<span class="text-muted">, class</span></pre>
    <p>the descriptor file can be taken as input even if
        it is not generated by this server.</p>

{% endblock %}
<!--主体内容-->
{% block content %}
    <!--任务提交-->
    <!--表单-->
    <form class="form-horizontal" action="{% url 'cal_screening:screening' %}" method="post"
          enctype="multipart/form-data">
        {% csrf_token %}
        <!--基本配置行-->
        <div class="row">
            <!--总面板-->
            <div class="panel panel-primary">
                <!--上传文件标题-->
                <div class="panel-heading text-center">
                    <h3 style="margin-bottom: 0;margin-top: 0">Screening Panel</h3>
                </div>
                <!--面板体-->
                <div class="panel-body" style="padding: 60px 15px;">
                    <!--左半部分-->
                    <div class="col-sm-6">
                        <!--上传描述符表单-->
                        <div class="form-group">
                            <!--标签宽度-->
                            <label for="csv-file" class="col-sm-3 control-label">training_set</label>
                            <!--选择框宽度-->
                            <div class="col-sm-9">
                                <!--在首尾加入符号-->
                                <div class="input-group">
                                    <!--加入符号-->
                                    <div class="input-group-addon" style="width: 60px;">.csv</div>
                                    <!--文件框-->
                                    <input id='descriptor_location' class="form-control"
                                           onclick="$('#csv-file').click();">
                                    <!--连接到选择文件按钮-->
                                    <label class="input-group-btn">
                                        <input type="button" id="i-check" value="Choose" class="btn btn-primary"
                                               onclick="$('#csv-file').click();">
                                    </label>
                                </div>
                            </div>
                            <!--选择文件按钮-->
                            <input class="form-control my_hide" type="file" name="descriptor_file" id='csv-file'
                                   accept=".csv"
                                   onchange="$('#descriptor_location').val($('#csv-file').val());"
                                   required="required">
                        </div>
                        <!--上传测试集描述符表单-->
                        <div class="form-group">
                            <!--标签宽度-->
                            <label for="test-csv-file" class="col-sm-3 control-label">test_set</label>
                            <!--选择框宽度-->
                            <div class="col-sm-9">
                                <!--在首尾加入符号-->
                                <div class="input-group">
                                    <!--加入符号-->
                                    <div class="input-group-addon" style="width: 60px;">.csv</div>
                                    <!--文件框-->
                                    <input id='test_descriptor_location' class="form-control"
                                           onclick="$('#test-csv-file').click();">
                                    <!--连接到选择文件按钮-->
                                    <label class="input-group-btn">
                                        <input type="button" id="i-check" value="Choose" class="btn btn-primary"
                                               onclick="$('#test-csv-file').click();">
                                    </label>
                                </div>
                            </div>
                            <!--选择文件按钮-->
                            <input class="form-control my_hide" type="file" name="test_descriptor_file"
                                   id='test-csv-file'
                                   accept=".csv"
                                   onchange="$('#test_descriptor_location').val($('#test-csv-file').val());"
                                   required="required">
                        </div>
                    </div>
                    <!--右半部分-->
                    <div class="col-sm-6">
                        <!--上传配置文件表单-->
                        <div class="form-group">
                            <!--标签宽度-->
                            <label for="config-file" class="col-sm-3 control-label">Config</label>
                            <!--选择框宽度-->
                            <div class="col-sm-9">
                                <!--在首尾加入符号-->
                                <div class="input-group">
                                    <!--文件框-->
                                    <input id='config_location' class="form-control"
                                           onclick="$('#config-file').click();">
                                    <!--连接到选择文件按钮-->
                                    <label class="input-group-btn">
                                        <input type="button" id="i-check" value="Choose" class="btn btn-primary"
                                               onclick="$('#config-file').click();">
                                    </label>
                                </div>
                            </div>
                            <!--选择文件按钮-->
                            <input class="form-control my_hide" type="file" name="config_file" id='config-file'
                                   accept=""
                                   onchange="$('#config_location').val($('#config-file').val());">
                        </div>
                        <!--Email-->
                        <div class="form-group">
                            <!--标签宽度-->
                            <label for="l-file" class="col-sm-3 control-label">Email <em>(optional)</em></label>
                            <!--选择框宽度-->
                            <div class="col-sm-9">
                                <!--在首尾加入符号-->
                                <div class="input-group" style="width: 100%">
                                    <!--文件框-->
                                    <input type="text" class="form-control" placeholder="xxx@zju.edu.cn"
                                           aria-describedby="basic-addon2" name="my_email">
                                    <!--加入符号-->
                                    <div class="input-group-addon" style="width: 73px">@</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--example-->
                <div class="panel-footer" style="font-size: 18px;padding: 12px 18px">
                    <strong>Example:</strong>
                    <a href="{% url 'cal_queue:example_download' 'descriptor_file' %}">Training Set</a>
                    |
                    <a href="{% url 'cal_queue:example_download' 'test_descriptor_file' %}">Test Set</a>
                    |
                    <a href="{% url 'cal_queue:example_download' 'config' %}">Config</a>
                    |
                    <a href="{% url 'cal_queue:example_download' 'screening' %}">Result</a>
                </div>
            </div>
        </div>
        <br/><br/>
        <!--提交任务行-->
        <div class="row">
            <!--提交任务-->
            <div class="col-sm-6 col-sm-offset-3 text-center">
                <button type="submit" id="submit_button" class="btn btn-success btn-lg">Submit</button>
            </div>
        </div>
    </form>
    <br/><br/><br/><br/>
{% endblock %}
<!--js-->
{% block js %}
    <script type="text/javascript">
        $(function () {
            //插件对表单验证
            $('form').bootstrapValidator({
                message: 'This value is not valid',
                excluded: [':disabled', ':hidden'],
                feedbackIcons: {
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'glyphicon glyphicon-remove',
                    validating: 'glyphicon glyphicon-refresh'
                },
                fields: {
                    //训练集描述符文件
                    descriptor_file: {
                        validators: {
                            notEmpty: {
                                message: 'Upload at least one descriptor file in csv format'
                            },
                            file: {
                                message: 'The file is not valid',
                                // 1024*1024 = 1MB
                                minSize: 0.008 * 1024 * 1024,  //最小8KB
                                maxSize: 10000 * 1024 * 1024,  //最大10GB
                            },
                            regexp: {
                                regexp: /.csv$/,
                                message: 'file extension error'
                            },
                        }
                    },
                    //测试集描述符文件
                    test_descriptor_file: {
                        validators: {
                            notEmpty: {
                                message: 'Upload at least one descriptor file in csv format'
                            },
                            file: {
                                message: 'The file is not valid',
                                // 1024*1024 = 1MB
                                minSize: 0.008 * 1024 * 1024,  //最小8KB
                                maxSize: 10000 * 1024 * 1024,  //最大10GB
                            },
                            regexp: {
                                regexp: /.csv$/,
                                message: 'file extension error'
                            },
                        }
                    },
                    //配置文件
                    config_file: {
                        validators: {
                            notEmpty: {
                                message: 'Upload at least one config file'
                            },
                            file: {
                                message: 'The file is not valid',
                                // 1024*1024 = 1MB
                                minSize: 0.0005 * 1024 * 1024,  //最小500K
                                maxSize: 1024 * 1024,  //最大1MB
                            },
                            regexp: {
                                regexp: /config$/,
                                message: 'file extension error'
                            },
                        }
                    },
                    //邮箱格式校验
                    my_email: {
                        validators: {
                            emailAddress: {
                                message: 'The input is not a valid email address'
                            }
                        }
                    },
                }
            });
        })
    </script>
{% endblock %}