ML-PLIC-Local/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include
from django.views import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('plic/', include('cal_docking.urls')),
    path('plic/', include('cal_descriptors.urls')),
    path('plic/', include('cal_model.urls')),
    path('plic/', include('cal_screening.urls')),
    path('plic/', include('cal_pipline.urls')),
    path('plic/', include('cal_queue.urls')),
    # 通过URL获取分子图片等文件
    re_path(r'^plic/submitted_files/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    # 获取静态文件
    re_path(r'^plic/static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
]

cal_descriptors/urls.py
#!usr/bin/env python
# -*- coding:utf-8 -*-
from django.urls import path
from . import views
app_name = 'cal_descriptors'
urlpatterns = [
    path('descriptors/', views.main, name='descriptors')
]

cal_docking/urls.py
#!usr/bin/env python
# -*- coding:utf-8 -*-
# author = zhang xujun
# time = 2020-07-15

from django.urls import path
from . import views
app_name = 'cal_docking'
urlpatterns = [
    path('docking/', views.main, name='docking')
]

cal_model/urls.py
#!usr/bin/env python
# -*- coding:utf-8 -*-
from django.urls import path
from . import views
app_name = 'cal_model'
urlpatterns = [
    path('modelling/', views.main, name='modelling')
]

cal_pipline/urls.py
#!usr/bin/env python
# -*- coding:utf-8 -*-
from django.urls import path
from . import views
app_name = 'cal_pipline'
urlpatterns = [
    path('', views.main, name='pipline')
]

cal_queue/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# author = zhang xujun
# time = 2020-07-18
from django.urls import path, re_path
from . import views
app_name = 'cal_queue'
urlpatterns = [
    path('queue', views.queue_page, name='queue'),  # 队列
    path('help', views.help, name='help'),  # 帮助
    path('paper', views.paper, name='paper'),  # 文章
    path('contact', views.contact, name='contact'),  # 联系
    path('viewed', views.viewed, name='viewed'),  # IP访问次数
    re_path(r'^results/(?P<job_id>job_[0-9]{8})', views.check_key, name='result'),  # 验证表单
    re_path(r'^results/(?P<job_id>b.*cadd$)', views.show_result, name='result_show'),  # 结果界面
    re_path(r'^results/(?P<job_id>b.*cadd)/download', views.download_result, name='download'),  # 结果界面下载结果文件
    re_path(r'^temp/job.*', views.temp, name='temp'),  # 各个任务完成后转跳的空白界面
    re_path(r'^temp/download/(?P<job_id>.*)', views.generate_key, name='generate_key'),  # 空白界面下载密钥
    re_path(r'^example/(?P<file_name>.*)', views.example_download, name='example_download'),  # 下载example 文件
]

cal_screening/urls.py
#!usr/bin/env python
# -*- coding:utf-8 -*-
# author = zhang xujun
# time = 2020-07-15

from django.urls import path
from . import views
app_name = 'cal_screening'
urlpatterns = [
    path('screening/', views.main, name='screening')
]

cal_queue/models.py
from django.db import models

# Create your models here.

cal_queue/views.py
from django.shortcuts import render

# Create your views here.
import os
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect, Http404
from base_scripts.base_class import queue_result_base, global_base
from django.contrib import messages
from multiprocessing import Pool
import re


def temp(request):
    # 返回页面
    return render(request, 'temp/index.html')


def viewed(request):
    # 重定向
    return HttpResponseRedirect('https://www.revolvermaps.com/livestats/5z9d6s1pvmv/')


def paper(request):
    # 获取访问量
    this_job = queue_result_base.queue()
    total_viewed = this_job.get_total_viewed()
    context = {'total_viewed': total_viewed}
    # 返回页面
    return render(request, 'paper/index.html', context)


def help(request):
    # 获取访问量
    this_job = queue_result_base.queue()
    total_viewed = this_job.get_total_viewed()
    context = {'total_viewed': total_viewed}
    # 返回页面
    return render(request, 'help/index.html', context)


def contact(request):
    # 获取访问量
    this_job = queue_result_base.queue()
    total_viewed = this_job.get_total_viewed()
    context = {'total_viewed': total_viewed}
    # 返回页面
    return render(request, 'contact/index.html', context)


# 在temp页面生成密钥并返回下载，若存在邮箱，则把文件发送给邮箱
def generate_key(request, job_id):
    # 实例化对象
    this_result = queue_result_base.queue()
    # 获取密钥
    key_file = this_result.key_file.format(job_id)
    # 创建密钥
    this_result.write_key(job_id)
    # 实例化任务控制对象
    this_job = global_base.job_control(job_id)
    # 读取第一个表单
    job_form = this_job.read_config(job_type='#')
    # 若邮箱存在，则发送邮件
    if job_form.get('my_email', None):
        this_job.send_email(job_form['my_email'], job_id, this_job.email_submit_content, key_file)
    # 返回文件
    return this_result.download_file(dst_file=key_file, file_name='{}.rsa'.format(job_id))


# 每隔1h检测并判断是否发送邮件
def check_send_email():
    # 实例化对象
    this_queue = queue_result_base.queue()
    # 获取任务名
    job_shs = this_queue.get_jobs()
    job_ids = [i.split('/')[-3] for i in job_shs]
    # 多进程任务信息
    pool = Pool(28)
    pool.map(this_queue.finished_jobs, job_ids)
    pool.close()
    pool.join()


# 根据上传的密钥验证
def check_key(request, job_id):
    # 若提交表单，则进行计算
    if request.method == 'POST':
        # 实例化对象
        this_result = queue_result_base.queue()
        # 对比密码
        if this_result.check_passwd(request, job_id=job_id):  # 若密码正确
            # 对任务名加密形成结果网页的URL
            job_result_url = str(this_result.make_secure(content=job_id, encryption=True))
            # 循环替换转义字符
            for string, code in this_result.str2code.items():
                job_result_url = job_result_url.replace(string, code)
            # 判断末尾加上cadd，作为参数截至的标志
            job_result_url = job_result_url + 'cadd'
            # 重定向到结果页面
            return HttpResponseRedirect(job_result_url)
        else:  # 若密码不正确
            # 弹窗
            messages.success(request, 'Validation Failure!')
            # 重定向回队列页面
            return HttpResponseRedirect('../queue')
    # 未提交表单，渲染空白页面
    else:
        return HttpResponseRedirect('../queue')


#  获取对应链接后渲染对应结果界面
def show_result(request, job_id):
    # 实例化对象
    this_result = queue_result_base.queue()
    # 换回问号
    # 循环把转义字符换回正常符号
    for string, code in this_result.str2code.items():
        job_id = job_id.replace(code, string)
    job_id = job_id.replace('cadd', '')  # 去掉后缀
    # 解密
    job_id = eval(job_id)  # 从字符串转成二进制
    job_id = this_result.make_secure(job_id, encryption=False)  # 解密
    # 获取任务类型
    this_result = queue_result_base.result(job_id)
    job_type = this_result.get_job_type()
    # 获取访问量
    total_viewed = this_result.get_total_viewed()
    # 先判断是否为pipeline
    if job_type == 'pipeline':
        # 实例化pipeline对象
        this_pipeline = global_base.pipline_control(job_id)
        # 判断是否对接和建模
        docking = this_pipeline.whether_dock()
        modelling = this_pipeline.whether_modelling()
        # 建模
        if modelling:
            model_metrics, feature, importance, parameter_names, parameters, lig_infos, each_interaction_static, interaction_res_frequency = this_result.deal_pipline()  # 获取信息
            # 获取数据
            context = {'job_type': job_type, 'job_id': job_id, 'lig_infos': lig_infos,
                       'each_interaction_static': each_interaction_static,
                       'interaction_rec_frequency': interaction_res_frequency, 'model_metrics': model_metrics,
                       'feature': feature, 'importance': importance, 'parameter_names': parameter_names,
                       'parameters': parameters, 'total_viewed': total_viewed}
            return render(request, 'result/index.html', context)  # 对应的路径为 /asfp/results/... 会报错，但是不影响渲染
        elif docking:  # 若不建模但是对接
            job_type = 'docking'  # 任务类型改为对接
        else:  # 不建模且不对接
            job_type = 'descriptors'  # 任务类型改为描述符提取
    # 若pipline未建模或者不是pipeline，再判断其他任务
    if job_type == 'docking':  # 对接 或者 pipeline进行对接未建模
        lig_infos, each_interaction_static, interaction_res_frequency = this_result.deal_docking()  # 获取信息
        # 获取数据
        context = {'job_type': job_type, 'job_id': job_id, 'lig_infos': lig_infos,
                   'each_interaction_static': each_interaction_static,
                   'interaction_rec_frequency': interaction_res_frequency, 'total_viewed': total_viewed}
        return render(request, 'result/index.html', context)  # 对应的路径为 /asfp/results/... 会报错，但是不影响渲染
    elif job_type == 'descriptors':  # 计算描述符 返回结果文件  descriptor 或者 pipeline未对接未建模
        return this_result.result_download()
    elif job_type == 'modelling':  # 建模
        model_metrics, feature, importance, parameter_names, parameters = this_result.deal_modelling()  # 获取信息
        # 获取数据
        context = {'job_type': job_type, 'job_id': job_id, 'model_metrics': model_metrics, 'feature': feature,
                   'importance': importance, 'total_viewed': total_viewed,
                   'parameter_names': parameter_names, 'parameters': parameters}
        return render(request, 'result/index.html', context)  # 对应的路径为 /asfp/results/... 会报错，但是不影响渲染
    elif job_type == 'screening':  # 虚筛 返回结果文件
        return this_result.result_download()


# 结果界面获取下载文件
#  获取对应链接后渲染对应结果界面
def download_result(request, job_id):
    # 实例化对象
    this_result = queue_result_base.queue()
    # 循环把转义字符换回正常符号
    for string, code in this_result.str2code.items():
        job_id = job_id.replace(code, string)
    job_id = job_id.replace('cadd', '')  # 去掉后缀
    # 解密
    job_id = eval(job_id)  # 从字符串转成二进制
    job_id = this_result.make_secure(job_id, encryption=False)  # 解密
    # 实例化任务对象
    this_result = queue_result_base.result(job_id)
    # 下载文件
    return this_result.result_download()


# 排队系统
def queue(request):  # 获取渲染页面所需数据
    # 实例化对象
    this_queue = queue_result_base.queue()
    # 获取访问量
    total_viewed = this_queue.get_total_viewed()
    # 根据sh文件获取任务名
    job_shs = this_queue.get_jobs()
    # 多进程任务信息
    pool = Pool(28)
    job_infos = pool.map(this_queue.get_job_info, job_shs)
    pool.close()
    pool.join()
    # 根据时间信息排序
    job_infos.sort(key=lambda x: x[-1], reverse=True)
    # 获取分页信息
    page_obj = this_queue.split_pages(request, job_infos)
    # 返回给页面的信息
    context = {'jobs': page_obj.object_list, 'page_obj': page_obj, 'start': page_obj.start_index() - 1,
               'total_viewed': total_viewed}
    # 返回
    return context


def queue_page(request):  # 渲染排队页面
    # 获取数据
    context = queue(request)
    # 渲染页面
    return render(request, 'queue/index.html', context)


# example 文件下载
def example_download(request, file_name):
    # 实例化对象
    this_queue = queue_result_base.queue()
    # 检查文件名是否正确
    if file_name not in this_queue.download_file_extension:
        raise Http404('Bad URL')
    # 定义需要下载的文件
    dst_file = this_queue.file_for_download.format(file_name, this_queue.download_file_extension[file_name])
    # 文件名字
    file_name = 'example_{}'.format(dst_file.split('/')[-1])
    # 下载文件
    return this_queue.download_file(dst_file=dst_file, file_name=file_name)

cal_queue/templates/queue/base.html
<!DOCTYPE html>
{% load static %}
{% block static_tag %}
{% endblock %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--引入bootstrap css-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <!--引入jqury js-->
    <script type="text/javascript" src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <!--引入bootstrap js-->
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <!--引入validator js-->
    <script type="text/javascript" src="{% static 'js/bootstrapValidator.min.js' %}"></script>
    <!--引入validator css-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrapValidator.min.css' %}">
    <!--自定义样式-->
    <style type="text/css">
        /*表单验证图标*/
        .form-control-feedback {
            padding-right: 100px;
        }

        /*表单验证文字*/
        .help-block {
            text-align: right;
            padding-right: 100px;
        }

        /*自定义隐藏格式*/
        .my_hide {
            width: 0;
            border: none;
            height: 0;
            position: absolute;
            visibility: hidden
        }
    </style>
    <!--允许标题可修改-->
    {% block title %}
        <title>ML-PLIC</title>
    {% endblock %}
</head>
<body>
<!--导航栏-->
<nav class="navbar navbar-default" style="margin-bottom: 0; font-size: 20px">
    <div class="container">
        <!-- logo -->
        <div class="navbar-header">
            <!--屏幕缩小时菜单按钮-->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!--logo-->
            <a class="navbar-brand" href="#" style="font-size: 28px; margin-top: 3.5px">ML-PLIC</a>
            <p class="navbar-text">ML-based protein-ligand interaction capturer</p>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right" style="margin-top: 3.5px">
                <!--首页-->
                <li><a href="{% url 'cal_pipline:pipline' %}">Home</a></li>
                <!--Services-->
                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                       aria-expanded="false">
                        Services <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu my_nav_dropdown_menu" style="font-size:20px;min-width: 60px">
                        <li ><a href="{% url 'cal_docking:docking' %}" style="padding: 1px 10px;">Docking</a></li>
                        <li><a href="{% url 'cal_descriptors:descriptors' %}" style="padding: 1px 10px;">Descriptors</a></li>
                        <li><a href="{% url 'cal_model:modelling' %}" style="padding: 1px 10px;">Modelling</a></li>
                        <li><a href="{% url 'cal_screening:screening' %}" style="padding: 1px 10px;">Screening</a></li>
                        <li><a href="{% url 'cal_pipline:pipline' %}" style="padding: 1px 10px;">Pipeline</a></li>
                    </ul>
                </li>
                <!--队列-->
                <li><a href="{% url 'cal_queue:queue' %}">Queue</a></li>
                <!--帮助-->
                <li><a href="{% url 'cal_queue:help' %}">Help</a></li>
                <!--paper-->
                <li><a href="{% url 'cal_queue:paper' %}">Paper</a></li>
                <!--Contact-->
                <li><a href="{% url 'cal_queue:contact' %}">Contact</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<!--内容-->
<!--可替换内容-->
{% block global_content %}
{% endblock %}
<!--footer-->
<nav class="navbar-default navbar-fixed-bottom">
    <div class="container">
        <div class="col-sm-10 col-sm-offset-2">
            <!-- 版权 -->
            <a class="navbar-brand" style="font-size: 16px">Copyright © 2019-2020 Tingjun Hou's Group All Rights
                Reserved | Total Views:
                <!--访问量-->
                {{ total_viewed }}
            </a>
            <!--ip插件-->
            <span style="display: none"><script type="text/javascript"
                                                src="//rf.revolvermaps.com/0/0/3.js?i=5z9d6s1pvmv&amp;b=0&amp;s=40&amp;m=2&amp;cl=ffffff&amp;co=010020&amp;cd=aa0000&amp;v0=60&amp;v1=60&amp;r=1"
                                                async="async"></script>
            </span>
        </div>
    </div>
</nav>
</body>
<!--修改js-->
{% block js %}
{% endblock %}
<script type="text/javascript">
    /*页面加载即执行*/
    $(function () {
        /*根据页面URL激活导航栏*/
        var page_url = window.location.pathname;
        $('.my_tab li').each(function () {
            if ($(this).children('a').attr('href') === page_url) {
                $(this).addClass('active')
            }
        });
    });
    /*鼠标移动到菜单栏自动显示*/
    hoverMenuShow();
    //获取活性口袋的方法
    //提供坐标
    $('#provide_xyz').click(function () {
        //禁止文件上传按钮
        $('#crystal_uplpad').attr('disabled', 'disabled');
        //移除晶体结构的输入框
        $('.binding_sites').remove();
        //增加xyz输入框
        var input_box = '                                    <!--加入符号-->\n' +
            '                                    <div class="input-group-addon binding_sites" style="width: 60px">x,y,z</div>\n' +
            '                                    <!--文件框-->\n' +
            '                                    <input id=\'site_xyz\' type="text" class="form-control binding_sites"\n' +
            '                                           aria-describedby="basic-addon2" name="site_xyz" placeholder="16, 14, 3.8">';
        $('#binding_site').prepend(input_box);
    });
    //提供参考配体
    $('#provide_crystal').click(function () {
        //启用文件上传按钮
        $('#crystal_uplpad').removeAttr('disabled');
        //移除晶体结构的输入框
        $('.binding_sites').remove();
        //增加xyz输入框
        var input_box = '                                    <!--加入符号-->\n' +
            '                                    <div class="input-group-addon binding_sites" style="width: 60px">.mol2</div>\n' +
            '                                    <!--文件框-->\n' +
            '                                    <input id=\'cry_location\' class="form-control binding_sites"\n' +
            '                                           onclick="$(\'#c-file\').click();">';
        $('#binding_site').prepend(input_box);
    });
    //提供口袋残基
    $('#provide_res').click(function () {
        //禁止文件上传按钮
        $('#crystal_uplpad').attr('disabled', 'disabled');
        //移除晶体结构的输入框
        $('.binding_sites').remove();
        //增加xyz输入框
        var input_box = '                                    <!--加入符号-->\n' +
            '                                    <div class="input-group-addon binding_sites" style="width: 60px">.res</div>\n' +
            '                                    <!--文件框-->\n' +
            '                                    <input id=\'site_res\' type="text" class="form-control binding_sites"\n' +
            '                                           aria-describedby="basic-addon2" name="site_res" placeholder="HIS_14, THR_83, PHE_150">';
        $('#binding_site').prepend(input_box);
    });

    function hoverMenuShow() {
        let $btn = $('.dropdown');
        let $menu = $('.my_nav_dropdown_menu');
        // let $menu = $('.dropdown-menu');

        // 移入显示 原理是手动给 dropdown-menu 加入一个显示类
        $btn.mouseover(function () {
            $menu.addClass('show');
        });

        /*
        移出消失 原理是手动删除 dropdown-menu 的类

           这里需要注意两个细节：
           1、当我们移入下边的菜单栏的时候我们不让菜单栏消失，这里我们使用定时器。让它延迟100毫秒消失，如果在100毫秒内移入菜单栏, 那么我们就关闭定时器，dropdown-menu就不会消失
           2、当我们从下边的菜单栏再次移入按钮的时候，也不能让菜单栏消失。原理同上

        */
        $btn.mouseout(function () {
            $hide = setTimeout(function () {
                // 移入菜单栏，取消隐藏
                $menu.mouseover(function () {
                    clearTimeout($hide);
                });
                // 再次移入按钮，取消定时器，不让其隐藏。
                $btn.mouseover(function () {
                    clearTimeout($hide);
                });
                $menu.removeClass('show');
            }, 100);
        })
    }
</script>
</html>